title: Two Cents
name: Luiz Borba
description: >-
  Blogging about programming, microservices and clojure❤️
keywords: [luiz borba blog clojure programming computer tech]
#baseurl: ""
#url: ""
domain: 'borba.blog.br'
twitter_username: luizborba
github_username:  borba
language: en

comments: false
discus: 
mathjax: false
diagram: true

paginate: 10
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-target-blank

target-blank:
   noreferrer: false